const events = [
  {
    name: "John Doe",
    eventName: "City Marathon",
    date: "2024-11-15",
    time: "07:00 AM",
    location: "Central Park, New York",
    price: 50,
    noEntries: 500,
    sport: "Running",
    image: "/images/img1.jpeg",
  },
  {
    name: "Jane Smith",
    eventName: "Mountain Biking Challenge",
    date: "2024-10-20",
    time: "09:00 AM",
    location: "Rocky Mountains, Colorado",
    price: 75,
    noEntries: 200,
    sport: "Cycling",
    image: "/images/img2.jpeg",
  },
  {
    name: "Alex Johnson",
    eventName: "Swim Across the Bay",
    date: "2024-12-05",
    time: "06:00 AM",
    location: "San Francisco Bay, California",
    price: 60,
    noEntries: 150,
    sport: "Swimming",
    image: "/images/img11.jpg",
  },
  {
    name: "Emma Davis",
    eventName: "Basketball League Finals",
    date: "2024-10-14",
    time: "05:00 PM",
    location: "Madison Square Garden, New York",
    price: 120,
    noEntries: 1000,
    sport: "Basketball",
    image: "/images/img8.jpeg",
  },
  {
    name: "Michael Brown",
    eventName: "Ultimate Frisbee Championship",
    date: "2024-11-01",
    time: "03:00 PM",
    location: "Golden Gate Park, San Francisco",
    price: 30,
    noEntries: 300,
    sport: "Frisbee",
    image: "/images/img1.jpeg",
  },
  {
    name: "Sophia Wilson",
    eventName: "Yoga in the Park",
    date: "2024-09-28",
    time: "08:00 AM",
    location: "Millennium Park, Chicago",
    price: 20,
    noEntries: 100,
    sport: "Yoga",
    image: "/images/img5.jpeg",
  },
  {
    name: "Liam Martinez",
    eventName: "City Soccer Tournament",
    date: "2024-10-05",
    time: "02:00 PM",
    location: "Dodger Stadium, Los Angeles",
    price: 45,
    noEntries: 600,
    sport: "Soccer",
    image: "/images/img6.jpeg",
  },
  {
    name: "Olivia Garcia",
    eventName: "Tennis Open",
    date: "2024-10-22",
    time: "11:00 AM",
    location: "Wimbledon, London",
    price: 150,
    noEntries: 800,
    sport: "Tennis",
    image: "/images/img7.jpeg",
  },
  {
    name: "William Taylor",
    eventName: "CrossFit Challenge",
    date: "2024-11-08",
    time: "10:00 AM",
    location: "CrossFit Arena, Miami",
    price: 85,
    noEntries: 400,
    sport: "CrossFit",
    image: "/images/img8.jpeg",
  },
  {
    name: "Isabella White",
    eventName: "Skateboarding Showdown",
    date: "2024-12-01",
    time: "04:00 PM",
    location: "Venice Beach, California",
    price: 25,
    noEntries: 250,
    sport: "Skateboarding",
    image: "/images/img3.jpeg",
  },
];

const eventsArray = [
  {
    title: "Start playing in sports events",
    image: "/images/carousel1 (1).svg",
    buttontext:"View My Profile",
    buttoncolor:"purple"
  },
  {
    title: "Host your Event with Us",
    image: "/images/carousel1 (2).svg",
    buttontext:"Create Your Event",
    buttoncolor:"yellow"
  },
  // {
  //   title: "Features Event Poster (Gold/Premium)",
  //   image: "/images/carousel1 (3).svg",
  //   buttontext:"Register Now",
  //   buttoncolor:"yellow"
  // },
  // {
  //   title: "Features Event Poster (Gold/Premium)",
  //   image: "/images/carousel1 (4).svg",
  //   buttontext:"Register Now",
  //   buttoncolor:"yellow"
  // },
  // {
  //   title: "Features Event Poster (Gold/Premium)",
  //   image: "/images/carousel1 (5).svg",
  //   buttontext:"Register Now",
  //   buttoncolor:"yellow"
  // },
];

const videoEventData = [
  {
    image: "/images/img7.jpeg",
    gifUrl:
      "https://media.giphy.com/media/l2JhKrvxWZprxpf8I/giphy.gif?cid=ecf05e47kl3t3hnjs3leywfiozx8rjvug69rhgdw2ysymdo6&ep=v1_gifs_related&rid=giphy.gif&ct=g",
    date: "October 10, 2024",
    name: "John Doe",
    eventname: "Basketball",
    location: "City Stadium",
    time: "6:00 PM",
    noOfEntries: 50,
    sport: "Basketball",
    price: 20,
    noEntries: 5,
  },
  {
    image: "/images/img3.jpeg",
    gifUrl:
      "https://media.giphy.com/media/5CAp3D1POATjG/giphy.gif?cid=ecf05e47j094k4ufa9rjk7scer9jw1evubrxnudqwq03iqbn&ep=v1_gifs_related&rid=giphy.gif&ct=g",
    date: "October 11, 2024",
    name: "Jane Smith",
    eventname: "Soccer",
    location: "City Stadium",
    time: "7:00 PM",
    noOfEntries: 60,
    sport: "Soccer",
    price: 25,
    noEntries: 3,
  },
  {
    image: "/images/img10.jpeg",
    gifUrl:
      "https://media.giphy.com/media/zpWLhHAQM9EyfeDTUx/giphy.gif?cid=790b76118vt01olwk8xg25tt9gevyhc1ragpvvig8u1lwvfu&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    date: "October 12, 2024",
    name: "Tom Brown",
    eventname: "Marathon",
    location: "Downtown Arena",
    time: "8:00 PM",
    noOfEntries: 40,
    sport: "Marathon",
    price: 30,
    noEntries: 4,
  },
  {
    image: "/images/img13.jpeg",
    gifUrl:
      "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWlodTF3MjJ3NnJiY3Rlc2J0ZmE0c28yeWoxc3gxY2VtZzA5ejF1NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/syEfLvksYQnmM/giphy.gif",
    date: "October 13, 2024",
    name: "Emily Johnson",
    eventname: "Tennis",
    location: "Community Park",
    time: "5:00 PM",
    noOfEntries: 70,
    sport: "Tennis",
    price: 15,
    noEntries: 2,
  },
  {
    image: "/images/img5.jpeg",
    gifUrl: "https://media.giphy.com/media/3o7aD2saXrDHeY6R0A/giphy.gif",
    date: "October 14, 2024",
    name: "Mike Davis",
    eventname: "Amazing Sports Event 5",
    location: "National Stadium",
    time: "6:30 PM",
    noOfEntries: 55,
    sport: "Rugby",
    price: 22,
    noEntries: 6,
  },
  {
    image: "/images/img6.jpeg",
    gifUrl: "https://media.giphy.com/media/3o7aD2saXrDHeY6R0A/giphy.gif",
    date: "October 15, 2024",
    name: "Sarah Wilson",
    eventname: "Amazing Sports Event 6",
    location: "Central Field",
    time: "4:00 PM",
    noOfEntries: 30,
    sport: "Cricket",
    price: 18,
    noEntries: 3,
  },
  {
    image: "/images/img7.jpeg",
    gifUrl: "https://media.giphy.com/media/3o7aD2saXrDHeY6R0A/giphy.gif",
    date: "October 16, 2024",
    name: "Chris Lee",
    eventname: "Amazing Sports Event 7",
    location: "Uptown Gym",
    time: "9:00 AM",
    noOfEntries: 65,
    sport: "Volleyball",
    price: 20,
    noEntries: 5,
  },
  {
    image: "/images/img8.jpeg",
    gifUrl: "https://media.giphy.com/media/3o7aD2saXrDHeY6R0A/giphy.gif",
    date: "October 17, 2024",
    name: "Jessica Taylor",
    eventname: "Amazing Sports Event 8",
    location: "Riverfront Park",
    time: "2:00 PM",
    noOfEntries: 45,
    sport: "Hockey",
    price: 27,
    noEntries: 4,
  },
  {
    image: "/images/img9.jpeg",
    gifUrl: "https://media.giphy.com/media/3o7aD2saXrDHeY6R0A/giphy.gif",
    date: "October 18, 2024",
    name: "David Anderson",
    eventname: "Amazing Sports Event 9",
    location: "City Hall",
    time: "1:00 PM",
    noOfEntries: 50,
    sport: "Swimming",
    price: 15,
    noEntries: 7,
  },
  {
    image: "/images/img1.jpeg",
    gifUrl: "https://media.giphy.com/media/3o7aD2saXrDHeY6R0A/giphy.gif",
    date: "October 19, 2024",
    name: "Laura Martinez",
    eventname: "Amazing Sports Event 10",
    location: "Westside Track",
    time: "3:00 PM",
    noOfEntries: 75,
    sport: "Track and Field",
    price: 12,
    noEntries: 8,
  },
];


const data = { events, eventsArray, videoEventData };
export default data;
